import 'dart:async';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:printing/printing.dart';
import 'package:provider/provider.dart';

import '../../data/models/models.dart';
import '../../services/analytics_service.dart';
import '../auth/user_viewmodel.dart';
import '../resume/pdf_service.dart';
import '../resume/resume_edit_screen.dart';
import '../resume/resume_viewmodel.dart';
import '../resume/widgets/ai_consent_modal.dart';
import '../resume/widgets/resume_template_selector.dart';
import 'profile_viewmodel.dart';
import '../../core/widgets/pii_mask.dart';

/// Detail/editor screen for a saved resume, opened from the Profile
/// library. Has two modes:
///
///   - **Editable**: for resumes generated by the trail (title starts with
///     [ResumeViewModel.kTrailResumeBaseTitle]). Shows live preview of
///     the current [ResumeViewModel.resumeData], with controls for
///     template, language, manual edit and PDF export.
///   - **View-only**: for imported PDFs (any other title). Shows the
///     downloaded PDF bytes with share/delete only — there is no
///     structured content to edit.
class ResumeDetailScreen extends StatefulWidget {
  final SavedResume resume;

  const ResumeDetailScreen({super.key, required this.resume});

  @override
  State<ResumeDetailScreen> createState() => _ResumeDetailScreenState();
}

class _ResumeDetailScreenState extends State<ResumeDetailScreen> {
  bool _isGeneratingPdf = false;
  Uint8List? _viewOnlyPdfBytes;
  bool _isLoadingPdf = false;

  // Cache do preview renderizado. Regerada quando template, idioma ou
  // conteúdo do CV mudam (chave abaixo). Evita regerar o PDF a cada
  // rebuild trivial (ex: spinners da IA piscando).
  Uint8List? _previewBytes;
  String? _previewKey;
  bool _isRegeneratingPreview = false;

  bool get _isEditable =>
      widget.resume.title.startsWith(ResumeViewModel.kTrailResumeBaseTitle);

  @override
  void initState() {
    super.initState();
    if (!_isEditable) {
      _loadViewOnlyPdf();
    }
  }

  Future<void> _loadViewOnlyPdf() async {
    if (!mounted) return;
    setState(() => _isLoadingPdf = true);
    try {
      final profileVM = context.read<ProfileViewModel>();
      final bytes = await profileVM.downloadResumeBytes(widget.resume);
      if (!mounted) return;
      setState(() {
        _viewOnlyPdfBytes = bytes;
        _isLoadingPdf = false;
      });
    } catch (_) {
      if (mounted) setState(() => _isLoadingPdf = false);
    }
  }

  Future<void> _exportToPdf(UserProfile? user, ResumeData resume) async {
    setState(() => _isGeneratingPdf = true);
    try {
      final vm = context.read<ResumeViewModel>();
      await PdfService.generateResume(user, resume, vm.selectedTemplateId);
      Analytics.shared.cvExported(templateId: vm.selectedTemplateId);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Erro ao gerar PDF: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isGeneratingPdf = false);
    }
  }

  Future<bool> _checkAndShowAIConsent(
    BuildContext context,
    ResumeViewModel viewModel,
  ) async {
    final userVM = context.read<UserViewModel>();
    final user = userVM.user;
    if (user != null && user.aiConsent) return true;

    final completer = Completer<bool>();
    showGeneralDialog(
      context: context,
      barrierDismissible: false,
      pageBuilder: (context, anim1, anim2) => AIConsentModal(
        onAccept: () async {
          await userVM.updateAIConsent(true);
          if (context.mounted) Navigator.pop(context);
          completer.complete(true);
        },
        onCancel: () {
          Navigator.pop(context);
          completer.complete(false);
        },
      ),
    );
    return completer.future;
  }

  Future<void> _confirmDelete() async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Excluir currículo?'),
        content: Text('"${widget.resume.title}" será removido da sua biblioteca.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: const Text('Cancelar'),
          ),
          TextButton(
            onPressed: () => Navigator.pop(ctx, true),
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('Excluir'),
          ),
        ],
      ),
    );
    if (confirmed != true || !mounted) return;
    final profileVM = context.read<ProfileViewModel>();
    await profileVM.deleteResume(widget.resume);
    if (mounted) Navigator.of(context).pop();
  }

  Future<void> _shareViewOnlyPdf() async {
    if (_viewOnlyPdfBytes == null) return;
    await Printing.sharePdf(
      bytes: _viewOnlyPdfBytes!,
      filename: '${widget.resume.title.replaceAll(' ', '_')}.pdf',
    );
  }

  @override
  Widget build(BuildContext context) {
    return PiiMask(child: Scaffold(
      backgroundColor: const Color(0xFFF3F4F6),
      appBar: AppBar(
        centerTitle: true,
        backgroundColor: Colors.white,
        foregroundColor: const Color(0xFF1F2937),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, size: 20),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text(
          widget.resume.title,
          style: GoogleFonts.outfit(
            fontWeight: FontWeight.bold,
            fontSize: 17,
            color: const Color(0xFF1F2937),
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.delete_outline_rounded, size: 22),
            tooltip: 'Excluir',
            onPressed: _confirmDelete,
          ),
        ],
      ),
      body: _isEditable ? _buildEditableBody() : _buildViewOnlyBody(),
    ));
  }

  // ── Editable mode (trail-generated CV) ─────────────────────────────
  Widget _buildEditableBody() {
    return Consumer2<UserViewModel, ResumeViewModel>(
      builder: (context, userVM, resumeVM, _) {
        final user = userVM.user;
        final resume = resumeVM.resumeData;

        return Stack(
          children: [
            Column(
              children: [
                _buildEditableToolbar(context, resumeVM),
                Expanded(
                  child: SingleChildScrollView(
                    padding: const EdgeInsets.fromLTRB(20, 16, 20, 110),
                    child: _buildPreviewCard(user, resume, resumeVM),
                  ),
                ),
              ],
            ),
            Positioned(
              bottom: 16,
              left: 20,
              right: 20,
              child: _buildBottomActionBar(context, user, resume, resumeVM),
            ),
          ],
        );
      },
    );
  }

  Widget _buildEditableToolbar(BuildContext context, ResumeViewModel vm) {
    return Container(
      color: Colors.white,
      padding: const EdgeInsets.fromLTRB(20, 12, 20, 12),
      child: Row(
        children: [
          GestureDetector(
            onTap: () {
              showModalBottomSheet(
                context: context,
                isScrollControlled: true,
                backgroundColor: Colors.transparent,
                builder: (_) => const ResumeTemplateSelector(),
              );
            },
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
              decoration: BoxDecoration(
                color: const Color(0xFFF3F4F6),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Row(
                children: [
                  const Icon(Icons.style_outlined, color: Color(0xFF4F46E5), size: 18),
                  const SizedBox(width: 6),
                  Text(
                    'Modelo',
                    style: GoogleFonts.inter(
                      fontSize: 13,
                      fontWeight: FontWeight.bold,
                      color: const Color(0xFF4F46E5),
                    ),
                  ),
                ],
              ),
            ),
          ),
          const SizedBox(width: 10),
          _LanguagePill(vm: vm),
          const Spacer(),
          if (vm.isGeneratingResume)
            const SizedBox(
              width: 22,
              height: 22,
              child: CircularProgressIndicator(strokeWidth: 2.5),
            ),
        ],
      ),
    );
  }

  Widget _buildPreviewCard(
    UserProfile? user,
    ResumeData? resume,
    ResumeViewModel vm,
  ) {
    // Chave que invalida o cache do preview: muda quando user troca de
    // template, idioma, ou quando o conteúdo do CV é regerado/editado.
    final key = resume == null
        ? null
        : '${vm.selectedTemplateId}|${vm.language}|${identityHashCode(resume)}';

    if (resume != null && key != _previewKey && !_isRegeneratingPreview) {
      _previewKey = key;
      _isRegeneratingPreview = true;
      // Regenerate off-frame so build doesn't block.
      WidgetsBinding.instance.addPostFrameCallback((_) async {
        try {
          final bytes = await PdfService.generateResumeBytes(
            user,
            resume,
            vm.selectedTemplateId,
          );
          if (!mounted) return;
          setState(() {
            _previewBytes = bytes;
            _isRegeneratingPreview = false;
          });
        } catch (e) {
          if (!mounted) return;
          setState(() => _isRegeneratingPreview = false);
        }
      });
    }

    return Container(
      width: double.infinity,
      height: 550,
      decoration: BoxDecoration(
        color: const Color(0xFFF3F4F6),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: Colors.grey[300]!),
      ),
      child: Stack(
        children: [
          if (_previewBytes != null)
            PdfPreview(
              build: (_) => _previewBytes!,
              useActions: false,
              canChangePageFormat: false,
              canChangeOrientation: false,
              canDebug: false,
              maxPageWidth: 600,
              padding: const EdgeInsets.all(12),
              scrollViewDecoration: const BoxDecoration(
                color: Color(0xFFF3F4F6),
              ),
              pdfPreviewPageDecoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(4),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withOpacity(0.12),
                    blurRadius: 14,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              loadingWidget: const Center(
                child: CircularProgressIndicator(color: Color(0xFF4F46E5)),
              ),
            )
          else
            const Center(
              child: CircularProgressIndicator(color: Color(0xFF4F46E5)),
            ),
          // Sutil indicação de "regerando" quando o user trocou template
          // e ainda estamos compondo o novo PDF — sem bloquear a visualização
          // atual (mostra o preview antigo até o novo estar pronto).
          if (_isRegeneratingPreview && _previewBytes != null)
            Positioned(
              top: 12,
              right: 12,
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                decoration: BoxDecoration(
                  color: Colors.black.withOpacity(0.7),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: const Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    SizedBox(
                      width: 12,
                      height: 12,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                      ),
                    ),
                    SizedBox(width: 6),
                    Text(
                      'Atualizando',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 11,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ],
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildBottomActionBar(
    BuildContext context,
    UserProfile? user,
    ResumeData? resume,
    ResumeViewModel vm,
  ) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
      decoration: BoxDecoration(
        color: const Color(0xFF1F2937),
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.2),
            blurRadius: 20,
            offset: const Offset(0, 10),
          ),
        ],
      ),
      child: Row(
        children: [
          IconButton(
            tooltip: 'Editar texto',
            onPressed: vm.resumeContent == null
                ? null
                : () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (_) => ResumeEditScreen(
                          initialContent: vm.resumeContent!,
                          onSave: (newContent) => vm.saveManualEdit(newContent),
                        ),
                      ),
                    );
                  },
            icon: Icon(
              Icons.edit_rounded,
              color: vm.resumeContent == null ? Colors.grey : Colors.white,
            ),
          ),
          IconButton(
            tooltip: 'Regerar com IA',
            onPressed: vm.isGeneratingResume
                ? null
                : () async {
                    if (await _checkAndShowAIConsent(context, vm)) {
                      vm.updateResumeWithAI();
                    }
                  },
            icon: const Icon(Icons.auto_awesome_rounded, color: Colors.white),
          ),
          const Spacer(),
          ElevatedButton.icon(
            onPressed: (_isGeneratingPdf || resume == null)
                ? null
                : () => _exportToPdf(user, resume),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.white,
              foregroundColor: Colors.black,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 12),
              elevation: 0,
            ),
            icon: _isGeneratingPdf
                ? const SizedBox(
                    width: 16,
                    height: 16,
                    child: CircularProgressIndicator(strokeWidth: 2, color: Colors.black),
                  )
                : const Icon(Icons.download_rounded, size: 18),
            label: Text(
              _isGeneratingPdf ? 'Gerando...' : 'Exportar PDF',
              style: const TextStyle(fontSize: 13, fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
    );
  }

  // ── View-only mode (imported PDF) ──────────────────────────────────
  Widget _buildViewOnlyBody() {
    if (_isLoadingPdf || _viewOnlyPdfBytes == null) {
      return const Center(
        child: CircularProgressIndicator(color: Color(0xFF4F46E5)),
      );
    }
    return Column(
      children: [
        Expanded(
          child: LayoutBuilder(
            builder: (context, constraints) {
              const double horizontalPadding = 16;
              const double maxWidth = 600;
              return InteractiveViewer(
                minScale: 0.5,
                maxScale: 4.0,
                child: PdfPreview(
                  build: (_) => _viewOnlyPdfBytes!,
                  useActions: false,
                  canChangePageFormat: false,
                  canChangeOrientation: false,
                  canDebug: false,
                  maxPageWidth: maxWidth,
                  padding: const EdgeInsets.symmetric(
                    vertical: 24,
                    horizontal: horizontalPadding,
                  ),
                  scrollViewDecoration:
                      const BoxDecoration(color: Color(0xFFF3F4F6)),
                  pdfPreviewPageDecoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(4),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.1),
                        blurRadius: 12,
                        offset: const Offset(0, 4),
                      ),
                    ],
                  ),
                  loadingWidget: const Center(
                    child: CircularProgressIndicator(color: Color(0xFF4F46E5)),
                  ),
                ),
              );
            },
          ),
        ),
        SafeArea(
          top: false,
          child: Padding(
            padding: const EdgeInsets.fromLTRB(20, 8, 20, 16),
            child: Row(
              children: [
                Expanded(
                  child: OutlinedButton.icon(
                    onPressed: _shareViewOnlyPdf,
                    icon: const Icon(Icons.share_rounded, size: 18),
                    label: const Text('Compartilhar'),
                    style: OutlinedButton.styleFrom(
                      foregroundColor: const Color(0xFF4F46E5),
                      side: const BorderSide(color: Color(0xFFE2E8F0), width: 1.5),
                      padding: const EdgeInsets.symmetric(vertical: 14),
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(14)),
                      textStyle: const TextStyle(
                        fontWeight: FontWeight.w800,
                        fontSize: 14,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}

/// Toggle PT/EN — regenera o CV com a IA na nova linguagem.
class _LanguagePill extends StatelessWidget {
  final ResumeViewModel vm;
  const _LanguagePill({required this.vm});

  static const _segWidth = 38.0;
  static const _segHeight = 28.0;

  Future<void> _switchTo(BuildContext context, String next) async {
    if (vm.language == next) return;
    final ok = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Trocar idioma do currículo?'),
        content: Text(
          next == 'en'
              ? 'Seu currículo será regerado em inglês com a IA. A versão em português fica salva.'
              : 'Seu currículo será regerado em português com a IA. A versão em inglês fica salva.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: const Text('Cancelar'),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(ctx, true),
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF4F46E5),
              foregroundColor: Colors.white,
            ),
            child: Text(next == 'en' ? 'Gerar em inglês' : 'Gerar em português'),
          ),
        ],
      ),
    );
    if (ok != true) return;
    await vm.setLanguage(next);
  }

  @override
  Widget build(BuildContext context) {
    final isEn = vm.isEnglish;
    return Container(
      height: _segHeight,
      decoration: BoxDecoration(
        color: const Color(0xFFF3F4F6),
        borderRadius: BorderRadius.circular(_segHeight / 2),
      ),
      child: Stack(
        children: [
          AnimatedPositioned(
            duration: const Duration(milliseconds: 220),
            curve: Curves.easeOutCubic,
            left: isEn ? _segWidth : 0,
            top: 0,
            bottom: 0,
            child: Container(
              width: _segWidth,
              margin: const EdgeInsets.all(2),
              decoration: BoxDecoration(
                color: const Color(0xFF4F46E5),
                borderRadius: BorderRadius.circular(_segHeight / 2),
              ),
            ),
          ),
          Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              _segment(context, label: 'PT', selected: !isEn, target: 'pt'),
              _segment(context, label: 'EN', selected: isEn, target: 'en'),
            ],
          ),
        ],
      ),
    );
  }

  Widget _segment(
    BuildContext context, {
    required String label,
    required bool selected,
    required String target,
  }) {
    return GestureDetector(
      onTap: () => _switchTo(context, target),
      behavior: HitTestBehavior.opaque,
      child: SizedBox(
        width: _segWidth,
        height: _segHeight,
        child: Center(
          child: Text(
            label,
            style: TextStyle(
              color: selected ? Colors.white : const Color(0xFF6B7280),
              fontWeight: FontWeight.bold,
              fontSize: 12,
              letterSpacing: 0.5,
            ),
          ),
        ),
      ),
    );
  }
}
