import 'dart:async';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:printing/printing.dart';
import 'package:provider/provider.dart';

import '../../core/analytics/screen_tracking.dart';
import '../../core/constants/stage_colors.dart';
import '../../data/models/models.dart';
import '../../services/analytics_service.dart';
import '../auth/user_viewmodel.dart';
import '../jobs/models/adapted_resume.dart';
import '../jobs/pending_adapted_cv_tracker.dart';
import '../resume/services/resume_renderer.dart';
import '../resume/resume_edit_screen.dart';
import '../resume/resume_viewmodel.dart';
import '../resume/widgets/ai_consent_modal.dart';
import '../resume/widgets/resume_template_selector.dart';
import 'profile_viewmodel.dart';
import '../../core/widgets/pii_mask.dart';

/// Metadata dos 5 templates exibidos no seletor inline da biblioteca.
/// Espelha `_kAdaptedTemplates` em adapted_resume_preview_screen.dart —
/// se mudar lá, atualizar aqui também.
const List<_LibraryTemplateOption> _kLibraryTemplates = [
  _LibraryTemplateOption(
    id: 'harvard_ats',
    label: 'Harvard ATS',
    description: 'Clássico, ideal pra IB/Consulting/Corporate',
    thumbnail: 'assets/images/templates/harvard_ats.png',
  ),
  _LibraryTemplateOption(
    id: 'jakes_resume',
    label: "Jake's Resume",
    description: 'Tech/dev, FAANG-friendly',
    thumbnail: 'assets/images/templates/jakes_resume.png',
  ),
  _LibraryTemplateOption(
    id: 'forte_foundation',
    label: 'Forte Foundation',
    description: 'Banking/MBA, conservador',
    thumbnail: 'assets/images/templates/forte_foundation.png',
  ),
  _LibraryTemplateOption(
    id: 'one_page_compact',
    label: 'One-Page Compact',
    description: 'Estudante early-career, sans-serif moderno',
    thumbnail: 'assets/images/templates/one_page_compact.png',
  ),
  _LibraryTemplateOption(
    id: 'cobalt_modern',
    label: 'Cobalt Modern',
    description: '2 colunas com sidebar, sans-serif moderno, accent azul cobalt',
    thumbnail: 'assets/images/templates/cobalt_modern.png',
  ),
];

class _LibraryTemplateOption {
  final String id;
  final String label;
  final String description;
  final String thumbnail;
  const _LibraryTemplateOption({
    required this.id,
    required this.label,
    required this.description,
    required this.thumbnail,
  });
}

/// Detail/editor screen for a saved resume, opened from the Profile
/// library. Has two modes:
///
///   - **Editable**: for resumes generated by the trail (title starts with
///     [ResumeViewModel.kTrailResumeBaseTitle]). Shows live preview of
///     the current [ResumeViewModel.resumeData], with controls for
///     template, language, manual edit and PDF export.
///   - **View-only**: for imported PDFs (any other title). Shows the
///     downloaded PDF bytes with share/delete only — there is no
///     structured content to edit.
class ResumeDetailScreen extends StatefulWidget {
  final SavedResume resume;

  const ResumeDetailScreen({super.key, required this.resume});

  @override
  State<ResumeDetailScreen> createState() => _ResumeDetailScreenState();
}

class _ResumeDetailScreenState extends State<ResumeDetailScreen>
    with ScreenTrackingMixin {
  @override
  String get screenName => 'resume_detail';

  bool _isGeneratingPdf = false;
  Uint8List? _viewOnlyPdfBytes;
  bool _isLoadingPdf = false;

  // Cache do preview renderizado. Regerada quando template, idioma ou
  // conteúdo do CV mudam (chave abaixo). Evita regerar o PDF a cada
  // rebuild trivial (ex: spinners da IA piscando).
  Uint8List? _previewBytes;
  String? _previewKey;
  bool _isRegeneratingPreview = false;

  // Estado do 3º modo: "structured adapted" (CV salvo na biblioteca com
  // resume_data estruturado). Permite trocar template e persistir.
  late SavedResume _currentResume; // pode ser atualizado por updateResumeTemplate
  late String _selectedTemplateId; // template aplicado no PDF visível
  bool _isChangingTemplate = false; // disable UI enquanto re-render+upload

  bool get _isEditable =>
      widget.resume.title.startsWith(ResumeViewModel.kTrailResumeBaseTitle);

  /// True quando o CV salvo tem `resume_data` estruturado e veio da
  /// adaptação (source=adapted). Habilita o seletor de template inline
  /// na biblioteca + troca persistente. CVs antigos (resumeData=null)
  /// continuam view-only.
  bool get _isStructuredAdapted =>
      !_isEditable &&
      _currentResume.resumeData != null &&
      _currentResume.source == SavedResumeSource.adapted;

  @override
  void initState() {
    super.initState();
    _currentResume = widget.resume;
    // Default = template salvo no DB; fallback pra harvard_ats (template
    // mais antigo). Só usado quando _isStructuredAdapted.
    _selectedTemplateId = _currentResume.templateId ?? 'harvard_ats';
    if (!_isEditable) {
      _loadViewOnlyPdf();
    }
  }

  Future<void> _loadViewOnlyPdf() async {
    if (!mounted) return;
    setState(() => _isLoadingPdf = true);
    try {
      final profileVM = context.read<ProfileViewModel>();
      final bytes = await profileVM.downloadResumeBytes(_currentResume);
      if (!mounted) return;
      setState(() {
        _viewOnlyPdfBytes = bytes;
        _isLoadingPdf = false;
      });
    } catch (_) {
      if (mounted) setState(() => _isLoadingPdf = false);
    }
  }

  /// Troca o template do CV salvo: re-renderiza via ResumeRenderer com o
  /// `resume_data` persistido, faz upload no mesmo file_path, atualiza
  /// `template_id` no DB, e troca o PDF visível na tela.
  ///
  /// Idempotente: noop se newTemplateId == atual.
  Future<void> _changeTemplateForLibraryItem(String newTemplateId) async {
    if (newTemplateId == _selectedTemplateId) return;
    if (_currentResume.resumeData == null) return; // safety
    HapticFeedback.selectionClick();
    setState(() => _isChangingTemplate = true);
    try {
      final user = context.read<UserViewModel>().user;
      // Reconstrói ResumeData a partir do jsonb persistido.
      final resumeData = AdaptedResume.parseResumeData(_currentResume.resumeData!);
      // Re-render com o template novo.
      final rendered = await ResumeRenderer.render(
        userId: user?.id,
        user: user,
        fallbackResume: resumeData,
        templateId: newTemplateId,
      );
      // Persiste: sobrescreve PDF no Storage + atualiza template_id no DB.
      final profileVM = context.read<ProfileViewModel>();
      final updated = await profileVM.updateResumeTemplate(
        resume: _currentResume,
        newPdfBytes: rendered.bytes,
        newTemplateId: newTemplateId,
      );
      if (!mounted) return;
      setState(() {
        _currentResume = updated;
        _selectedTemplateId = newTemplateId;
        _viewOnlyPdfBytes = rendered.bytes;
        _isChangingTemplate = false;
      });
      // ignore: unawaited_futures
      Analytics.shared.cvTemplateChanged(templateId: newTemplateId);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            'Modelo trocado pra "${_kLibraryTemplates.firstWhere((t) => t.id == newTemplateId, orElse: () => _kLibraryTemplates.first).label}"',
          ),
          behavior: SnackBarBehavior.floating,
          backgroundColor: StageColors.brandCyan,
          duration: const Duration(seconds: 2),
        ),
      );
    } catch (e) {
      if (!mounted) return;
      setState(() => _isChangingTemplate = false);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Erro ao trocar modelo: $e'),
          behavior: SnackBarBehavior.floating,
          backgroundColor: Colors.red.shade600,
        ),
      );
    }
  }

  /// Bottom sheet com os 5 templates pra trocar o modelo de um CV salvo
  /// na biblioteca. Idêntico ao seletor da preview de adaptado pra UX
  /// consistente.
  void _openLibraryTemplatePicker() {
    HapticFeedback.lightImpact();
    showModalBottomSheet<void>(
      context: context,
      backgroundColor: Colors.white,
      isScrollControlled: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (sheetCtx) {
        return SafeArea(
          child: Padding(
            padding: const EdgeInsets.fromLTRB(16, 12, 16, 20),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Center(
                  child: Container(
                    width: 36,
                    height: 4,
                    margin: const EdgeInsets.only(bottom: 12),
                    decoration: BoxDecoration(
                      color: const Color(0xFFE5E7EB),
                      borderRadius: BorderRadius.circular(2),
                    ),
                  ),
                ),
                const Padding(
                  padding: EdgeInsets.symmetric(horizontal: 4),
                  child: Text(
                    'Trocar modelo',
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.w800,
                      color: Color(0xFF111827),
                    ),
                  ),
                ),
                const SizedBox(height: 4),
                const Padding(
                  padding: EdgeInsets.symmetric(horizontal: 4),
                  child: Text(
                    'O PDF será regerado com o modelo novo e substituído na biblioteca.',
                    style: TextStyle(fontSize: 12, color: Color(0xFF6B7280)),
                  ),
                ),
                const SizedBox(height: 16),
                ..._kLibraryTemplates.map((t) {
                  final isSelected = t.id == _selectedTemplateId;
                  return Padding(
                    padding: const EdgeInsets.only(bottom: 10),
                    child: InkWell(
                      borderRadius: BorderRadius.circular(12),
                      onTap: () {
                        Navigator.of(sheetCtx).pop();
                        _changeTemplateForLibraryItem(t.id);
                      },
                      child: Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: isSelected
                              ? StageColors.brandCyan.withOpacity(0.06)
                              : const Color(0xFFF9FAFB),
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(
                            color: isSelected
                                ? StageColors.brandCyan
                                : const Color(0xFFE5E7EB),
                            width: isSelected ? 1.5 : 1,
                          ),
                        ),
                        child: Row(
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(6),
                              child: Image.asset(
                                t.thumbnail,
                                width: 56,
                                height: 72,
                                fit: BoxFit.cover,
                                errorBuilder: (_, __, ___) => Container(
                                  width: 56,
                                  height: 72,
                                  color: const Color(0xFFE5E7EB),
                                  child: const Icon(
                                    Icons.description_outlined,
                                    color: Color(0xFF9CA3AF),
                                  ),
                                ),
                              ),
                            ),
                            const SizedBox(width: 12),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Row(
                                    children: [
                                      Expanded(
                                        child: Text(
                                          t.label,
                                          style: TextStyle(
                                            fontSize: 14,
                                            fontWeight: FontWeight.w700,
                                            color: isSelected
                                                ? StageColors.brandCyan
                                                : const Color(0xFF111827),
                                          ),
                                        ),
                                      ),
                                      if (isSelected)
                                        const Icon(
                                          Icons.check_circle_rounded,
                                          size: 18,
                                          color: StageColors.brandCyan,
                                        ),
                                    ],
                                  ),
                                  const SizedBox(height: 4),
                                  Text(
                                    t.description,
                                    style: const TextStyle(
                                      fontSize: 12,
                                      color: Color(0xFF6B7280),
                                      height: 1.3,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  );
                }),
              ],
            ),
          ),
        );
      },
    );
  }

  Future<void> _exportToPdf(UserProfile? user, ResumeData resume) async {
    setState(() => _isGeneratingPdf = true);
    try {
      final vm = context.read<ResumeViewModel>();
      final rendered = await ResumeRenderer.render(
        userId: user?.id,
        user: user,
        fallbackResume: resume,
        templateId: vm.selectedTemplateId,
      );
      final safeName = user?.name ?? 'profissional';
      await Printing.sharePdf(
        bytes: rendered.bytes,
        filename: 'curriculo_${safeName.replaceAll(' ', '_')}.pdf',
      );
      Analytics.shared.cvExported(templateId: vm.selectedTemplateId);
      // Ciclo completo de export — limpa o banner pendente (F2.5).
      // ignore: unawaited_futures
      PendingAdaptedCvTracker.shared.clear();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Erro ao gerar PDF: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isGeneratingPdf = false);
    }
  }

  Future<bool> _checkAndShowAIConsent(
    BuildContext context,
    ResumeViewModel viewModel,
  ) async {
    final userVM = context.read<UserViewModel>();
    final user = userVM.user;
    if (user != null && user.aiConsent) return true;

    final completer = Completer<bool>();
    showGeneralDialog(
      context: context,
      barrierDismissible: false,
      pageBuilder: (context, anim1, anim2) => AIConsentModal(
        onAccept: () async {
          await userVM.updateAIConsent(true);
          if (context.mounted) Navigator.pop(context);
          completer.complete(true);
        },
        onCancel: () {
          Navigator.pop(context);
          completer.complete(false);
        },
      ),
    );
    return completer.future;
  }

  Future<void> _confirmDelete() async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Excluir currículo?'),
        content: Text('"${widget.resume.title}" será removido da sua biblioteca.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: const Text('Cancelar'),
          ),
          TextButton(
            onPressed: () => Navigator.pop(ctx, true),
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('Excluir'),
          ),
        ],
      ),
    );
    if (confirmed != true || !mounted) return;
    final profileVM = context.read<ProfileViewModel>();
    await profileVM.deleteResume(widget.resume);
    if (mounted) Navigator.of(context).pop();
  }

  Future<void> _shareViewOnlyPdf() async {
    if (_viewOnlyPdfBytes == null) return;
    await Printing.sharePdf(
      bytes: _viewOnlyPdfBytes!,
      filename: '${widget.resume.title.replaceAll(' ', '_')}.pdf',
    );
  }

  @override
  Widget build(BuildContext context) {
    return PiiMask(child: Scaffold(
      backgroundColor: const Color(0xFFF3F4F6),
      appBar: AppBar(
        centerTitle: true,
        backgroundColor: Colors.white,
        foregroundColor: const Color(0xFF1F2937),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, size: 20),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text(
          widget.resume.title,
          style: TextStyle(fontFamily: 'Outfit', 
            fontWeight: FontWeight.bold,
            fontSize: 17,
            color: const Color(0xFF1F2937),
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.delete_outline_rounded, size: 22),
            tooltip: 'Excluir',
            onPressed: _confirmDelete,
          ),
        ],
      ),
      body: _isEditable ? _buildEditableBody() : _buildViewOnlyBody(),
    ));
  }

  // ── Editable mode (trail-generated CV) ─────────────────────────────
  Widget _buildEditableBody() {
    return Consumer2<UserViewModel, ResumeViewModel>(
      builder: (context, userVM, resumeVM, _) {
        final user = userVM.user;
        final resume = resumeVM.resumeData;

        return Stack(
          children: [
            Column(
              children: [
                _buildEditableToolbar(context, resumeVM),
                Expanded(
                  child: SingleChildScrollView(
                    padding: const EdgeInsets.fromLTRB(20, 16, 20, 110),
                    child: _buildPreviewCard(user, resume, resumeVM),
                  ),
                ),
              ],
            ),
            Positioned(
              bottom: 16,
              left: 20,
              right: 20,
              child: _buildBottomActionBar(context, user, resume, resumeVM),
            ),
          ],
        );
      },
    );
  }

  Widget _buildEditableToolbar(BuildContext context, ResumeViewModel vm) {
    return Container(
      color: Colors.white,
      padding: const EdgeInsets.fromLTRB(20, 12, 20, 12),
      child: Row(
        children: [
          GestureDetector(
            onTap: () {
              showModalBottomSheet(
                context: context,
                isScrollControlled: true,
                backgroundColor: Colors.transparent,
                builder: (_) => const ResumeTemplateSelector(),
              );
            },
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
              decoration: BoxDecoration(
                color: const Color(0xFFF3F4F6),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Row(
                children: [
                  const Icon(Icons.style_outlined, color: Color(0xFF4F46E5), size: 18),
                  const SizedBox(width: 6),
                  Text(
                    'Modelo',
                    style: TextStyle(fontFamily: 'Inter', 
                      fontSize: 13,
                      fontWeight: FontWeight.bold,
                      color: const Color(0xFF4F46E5),
                    ),
                  ),
                ],
              ),
            ),
          ),
          const SizedBox(width: 10),
          _LanguagePill(vm: vm),
          const Spacer(),
          if (vm.isGeneratingResume)
            const SizedBox(
              width: 22,
              height: 22,
              child: CircularProgressIndicator(strokeWidth: 2.5),
            ),
        ],
      ),
    );
  }

  Widget _buildPreviewCard(
    UserProfile? user,
    ResumeData? resume,
    ResumeViewModel vm,
  ) {
    // Chave que invalida o cache do preview: muda quando user troca de
    // template, idioma, ou quando o conteúdo do CV é regerado/editado.
    final key = resume == null
        ? null
        : '${vm.selectedTemplateId}|${vm.language}|${identityHashCode(resume)}';

    if (resume != null && key != _previewKey && !_isRegeneratingPreview) {
      _previewKey = key;
      _isRegeneratingPreview = true;
      // Regenerate off-frame so build doesn't block.
      WidgetsBinding.instance.addPostFrameCallback((_) async {
        try {
          final rendered = await ResumeRenderer.render(
            userId: user?.id,
            user: user,
            fallbackResume: resume,
            templateId: vm.selectedTemplateId,
          );
          if (!mounted) return;
          setState(() {
            _previewBytes = rendered.bytes;
            _isRegeneratingPreview = false;
          });
        } catch (e) {
          if (!mounted) return;
          setState(() => _isRegeneratingPreview = false);
        }
      });
    }

    return Container(
      width: double.infinity,
      height: 550,
      decoration: BoxDecoration(
        color: const Color(0xFFF3F4F6),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: Colors.grey[300]!),
      ),
      child: Stack(
        children: [
          if (_previewBytes != null)
            PdfPreview(
              build: (_) => _previewBytes!,
              useActions: false,
              canChangePageFormat: false,
              canChangeOrientation: false,
              canDebug: false,
              maxPageWidth: 600,
              padding: const EdgeInsets.all(12),
              scrollViewDecoration: const BoxDecoration(
                color: Color(0xFFF3F4F6),
              ),
              pdfPreviewPageDecoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(4),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withOpacity(0.12),
                    blurRadius: 14,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              loadingWidget: const Center(
                child: CircularProgressIndicator(color: Color(0xFF4F46E5)),
              ),
            )
          else
            const Center(
              child: CircularProgressIndicator(color: Color(0xFF4F46E5)),
            ),
          // Sutil indicação de "regerando" quando o user trocou template
          // e ainda estamos compondo o novo PDF — sem bloquear a visualização
          // atual (mostra o preview antigo até o novo estar pronto).
          if (_isRegeneratingPreview && _previewBytes != null)
            Positioned(
              top: 12,
              right: 12,
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                decoration: BoxDecoration(
                  color: Colors.black.withOpacity(0.7),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: const Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    SizedBox(
                      width: 12,
                      height: 12,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                      ),
                    ),
                    SizedBox(width: 6),
                    Text(
                      'Atualizando',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 11,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ],
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildBottomActionBar(
    BuildContext context,
    UserProfile? user,
    ResumeData? resume,
    ResumeViewModel vm,
  ) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
      decoration: BoxDecoration(
        color: const Color(0xFF1F2937),
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.2),
            blurRadius: 20,
            offset: const Offset(0, 10),
          ),
        ],
      ),
      child: Row(
        children: [
          IconButton(
            tooltip: 'Editar texto',
            onPressed: vm.resumeContent == null
                ? null
                : () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (_) => ResumeEditScreen(
                          initialContent: vm.resumeContent!,
                          onSave: (newContent) => vm.saveManualEdit(newContent),
                        ),
                      ),
                    );
                  },
            icon: Icon(
              Icons.edit_rounded,
              color: vm.resumeContent == null ? Colors.grey : Colors.white,
            ),
          ),
          IconButton(
            tooltip: 'Regerar com IA',
            onPressed: vm.isGeneratingResume
                ? null
                : () async {
                    if (await _checkAndShowAIConsent(context, vm)) {
                      vm.updateResumeWithAI();
                    }
                  },
            icon: const Icon(Icons.auto_awesome_rounded, color: Colors.white),
          ),
          const Spacer(),
          ElevatedButton.icon(
            onPressed: (_isGeneratingPdf || resume == null)
                ? null
                : () => _exportToPdf(user, resume),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.white,
              foregroundColor: Colors.black,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 12),
              elevation: 0,
            ),
            icon: _isGeneratingPdf
                ? const SizedBox(
                    width: 16,
                    height: 16,
                    child: CircularProgressIndicator(strokeWidth: 2, color: Colors.black),
                  )
                : const Icon(Icons.download_rounded, size: 18),
            label: Text(
              _isGeneratingPdf ? 'Gerando...' : 'Exportar PDF',
              style: const TextStyle(fontSize: 13, fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
    );
  }

  // ── View-only mode (imported PDF) ──────────────────────────────────
  Widget _buildViewOnlyBody() {
    if (_isLoadingPdf || _viewOnlyPdfBytes == null) {
      return const Center(
        child: CircularProgressIndicator(color: Color(0xFF4F46E5)),
      );
    }
    return Stack(
      children: [
        Column(
          children: [
            // Toolbar "Trocar modelo" — visível só pra CVs adapted com
            // resume_data persistido (migration 20260526+). CVs antigos
            // ficam só com share/delete.
            if (_isStructuredAdapted) _buildLibraryTemplateToolbar(),
            Expanded(
              child: LayoutBuilder(
                builder: (context, constraints) {
                  const double horizontalPadding = 16;
                  const double maxWidth = 600;
                  return InteractiveViewer(
                    minScale: 0.5,
                    maxScale: 4.0,
                    child: PdfPreview(
                      // Key força recriação do PdfPreview quando bytes mudam
                      // (troca de template). Sem isso o widget pode cachear
                      // o PDF anterior internamente.
                      key: ValueKey('view_only_pdf_${_viewOnlyPdfBytes!.length}'),
                      build: (_) => _viewOnlyPdfBytes!,
                      useActions: false,
                      canChangePageFormat: false,
                      canChangeOrientation: false,
                      canDebug: false,
                      maxPageWidth: maxWidth,
                      padding: const EdgeInsets.symmetric(
                        vertical: 24,
                        horizontal: horizontalPadding,
                      ),
                      scrollViewDecoration:
                          const BoxDecoration(color: Color(0xFFF3F4F6)),
                      pdfPreviewPageDecoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(4),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.black.withOpacity(0.1),
                            blurRadius: 12,
                            offset: const Offset(0, 4),
                          ),
                        ],
                      ),
                      loadingWidget: const Center(
                        child: CircularProgressIndicator(color: Color(0xFF4F46E5)),
                      ),
                    ),
                  );
                },
              ),
            ),
            SafeArea(
              top: false,
              child: Padding(
                padding: const EdgeInsets.fromLTRB(20, 8, 20, 16),
                child: Row(
                  children: [
                    Expanded(
                      child: OutlinedButton.icon(
                        onPressed: _shareViewOnlyPdf,
                        icon: const Icon(Icons.share_rounded, size: 18),
                        label: const Text('Compartilhar'),
                        style: OutlinedButton.styleFrom(
                          foregroundColor: const Color(0xFF4F46E5),
                          side: const BorderSide(color: Color(0xFFE2E8F0), width: 1.5),
                          padding: const EdgeInsets.symmetric(vertical: 14),
                          shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(14)),
                          textStyle: const TextStyle(
                            fontWeight: FontWeight.w800,
                            fontSize: 14,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
        // Overlay enquanto a troca de template está rolando (re-render +
        // upload). Bloqueia interação pra evitar double-tap em outro
        // template no meio do upload.
        if (_isChangingTemplate)
          Positioned.fill(
            child: Container(
              color: Colors.black.withOpacity(0.35),
              child: const Center(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    SizedBox(
                      height: 36,
                      width: 36,
                      child: CircularProgressIndicator(
                        strokeWidth: 3,
                        color: Colors.white,
                      ),
                    ),
                    SizedBox(height: 16),
                    Text(
                      'Aplicando novo modelo...',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
      ],
    );
  }

  /// Toolbar acima do PDF com o template atual + botão pra trocar.
  /// Renderizada só em modo `_isStructuredAdapted`.
  Widget _buildLibraryTemplateToolbar() {
    final selected = _kLibraryTemplates.firstWhere(
      (t) => t.id == _selectedTemplateId,
      orElse: () => _kLibraryTemplates.first,
    );
    return Container(
      color: Colors.white,
      padding: const EdgeInsets.fromLTRB(20, 10, 20, 10),
      child: Row(
        children: [
          const Text(
            'Modelo:',
            style: TextStyle(
              fontSize: 13,
              color: Color(0xFF6B7280),
              fontWeight: FontWeight.w600,
            ),
          ),
          const SizedBox(width: 8),
          Expanded(
            child: GestureDetector(
              onTap: _isChangingTemplate ? null : _openLibraryTemplatePicker,
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                decoration: BoxDecoration(
                  color: const Color(0xFFF3F4F6),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: Row(
                  children: [
                    const Icon(
                      Icons.dashboard_customize_rounded,
                      size: 16,
                      color: Color(0xFF374151),
                    ),
                    const SizedBox(width: 6),
                    Expanded(
                      child: Text(
                        selected.label,
                        overflow: TextOverflow.ellipsis,
                        style: const TextStyle(
                          fontSize: 13,
                          fontWeight: FontWeight.w700,
                          color: Color(0xFF111827),
                        ),
                      ),
                    ),
                    const SizedBox(width: 4),
                    const Icon(
                      Icons.expand_more_rounded,
                      size: 16,
                      color: Color(0xFF6B7280),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

/// Toggle PT/EN — regenera o CV com a IA na nova linguagem.
class _LanguagePill extends StatelessWidget {
  final ResumeViewModel vm;
  const _LanguagePill({required this.vm});

  static const _segWidth = 38.0;
  static const _segHeight = 28.0;

  Future<void> _switchTo(BuildContext context, String next) async {
    if (vm.language == next) return;
    final ok = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Trocar idioma do currículo?'),
        content: Text(
          next == 'en'
              ? 'Seu currículo será regerado em inglês com a IA. A versão em português fica salva.'
              : 'Seu currículo será regerado em português com a IA. A versão em inglês fica salva.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: const Text('Cancelar'),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(ctx, true),
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF4F46E5),
              foregroundColor: Colors.white,
            ),
            child: Text(next == 'en' ? 'Gerar em inglês' : 'Gerar em português'),
          ),
        ],
      ),
    );
    if (ok != true) return;
    await vm.setLanguage(next);
  }

  @override
  Widget build(BuildContext context) {
    final isEn = vm.isEnglish;
    return Container(
      height: _segHeight,
      decoration: BoxDecoration(
        color: const Color(0xFFF3F4F6),
        borderRadius: BorderRadius.circular(_segHeight / 2),
      ),
      child: Stack(
        children: [
          AnimatedPositioned(
            duration: const Duration(milliseconds: 220),
            curve: Curves.easeOutCubic,
            left: isEn ? _segWidth : 0,
            top: 0,
            bottom: 0,
            child: Container(
              width: _segWidth,
              margin: const EdgeInsets.all(2),
              decoration: BoxDecoration(
                color: const Color(0xFF4F46E5),
                borderRadius: BorderRadius.circular(_segHeight / 2),
              ),
            ),
          ),
          Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              _segment(context, label: 'PT', selected: !isEn, target: 'pt'),
              _segment(context, label: 'EN', selected: isEn, target: 'en'),
            ],
          ),
        ],
      ),
    );
  }

  Widget _segment(
    BuildContext context, {
    required String label,
    required bool selected,
    required String target,
  }) {
    return GestureDetector(
      onTap: () => _switchTo(context, target),
      behavior: HitTestBehavior.opaque,
      child: SizedBox(
        width: _segWidth,
        height: _segHeight,
        child: Center(
          child: Text(
            label,
            style: TextStyle(
              color: selected ? Colors.white : const Color(0xFF6B7280),
              fontWeight: FontWeight.bold,
              fontSize: 12,
              letterSpacing: 0.5,
            ),
          ),
        ),
      ),
    );
  }
}
