-- skills taxonomy (auditoria P5) — GERADO por tools/skills_taxonomy/generate_seed.py
-- a partir de taxonomy.json v1. NÃO editar à mão: editar o JSON e regerar.
--
-- Catálogo canônico de skills + mapa de aliases (texto livre normalizado → canônica)
-- + profile_skills.canonical_skill_id (name CRU permanece a verdade, padrão institution_id)
-- + trigger que normaliza em TODO insert/update (pega qualquer versão de client) + backfill.
-- 165 canônicas, 401 aliases.

create table if not exists public.skills_catalog (
  id uuid primary key default gen_random_uuid(),
  canonical_name text not null unique,
  category text not null check (category in ('hard','soft','tool','language')),
  created_at timestamptz not null default now()
);

create table if not exists public.skill_aliases (
  alias_normalized text primary key,
  canonical_skill_id uuid not null references public.skills_catalog(id) on delete cascade
);

alter table public.profile_skills
  add column if not exists canonical_skill_id uuid references public.skills_catalog(id) on delete set null;

create index if not exists profile_skills_canonical_idx on public.profile_skills(canonical_skill_id);
create index if not exists skill_aliases_canon_idx on public.skill_aliases(canonical_skill_id);

-- Reference data pública (nomes de skill, não-PII): RLS on + leitura p/ todos os papéis.
alter table public.skills_catalog enable row level security;
alter table public.skill_aliases enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='skills_catalog' and policyname='skills_catalog_read') then
    create policy skills_catalog_read on public.skills_catalog for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='skill_aliases' and policyname='skill_aliases_read') then
    create policy skill_aliases_read on public.skill_aliases for select using (true);
  end if;
end $$;
grant select on public.skills_catalog to anon, authenticated, service_role;
grant select on public.skill_aliases to anon, authenticated, service_role;

-- ── Seed: catálogo ──────────────────────────────────────────────────────────
insert into public.skills_catalog (canonical_name, category) values
  ('Excel', 'tool'),
  ('Word', 'tool'),
  ('PowerPoint', 'tool'),
  ('Outlook', 'tool'),
  ('Pacote Office', 'tool'),
  ('Google Workspace', 'tool'),
  ('Canva', 'tool'),
  ('Figma', 'tool'),
  ('Power BI', 'tool'),
  ('Photoshop', 'tool'),
  ('Illustrator', 'tool'),
  ('After Effects', 'tool'),
  ('Premiere', 'tool'),
  ('Pacote Adobe', 'tool'),
  ('CapCut', 'tool'),
  ('Git', 'tool'),
  ('Docker', 'tool'),
  ('VS Code', 'tool'),
  ('Postman', 'tool'),
  ('Insomnia', 'tool'),
  ('Jira', 'tool'),
  ('Trello', 'tool'),
  ('Notion', 'tool'),
  ('Linux', 'tool'),
  ('Windows', 'tool'),
  ('macOS', 'tool'),
  ('AutoCAD', 'tool'),
  ('Revit', 'tool'),
  ('SketchUp', 'tool'),
  ('SolidWorks', 'tool'),
  ('SAP', 'tool'),
  ('TOTVS', 'tool'),
  ('Salesforce', 'tool'),
  ('ServiceNow', 'tool'),
  ('Tableau', 'tool'),
  ('Power Automate', 'tool'),
  ('Power Apps', 'tool'),
  ('WordPress', 'tool'),
  ('Vercel', 'tool'),
  ('Vite', 'tool'),
  ('Maven', 'tool'),
  ('IntelliJ IDEA', 'tool'),
  ('Microsoft Teams', 'tool'),
  ('Miro', 'tool'),
  ('Omie', 'tool'),
  ('Tasy', 'tool'),
  ('Zabbix', 'tool'),
  ('n8n', 'tool'),
  ('OBS Studio', 'tool'),
  ('Firebase', 'tool'),
  ('CRM', 'tool'),
  ('ERP', 'tool'),
  ('Oracle', 'tool'),
  ('Informática básica', 'tool'),
  ('Planilhas', 'tool'),
  ('Python', 'hard'),
  ('JavaScript', 'hard'),
  ('TypeScript', 'hard'),
  ('Java', 'hard'),
  ('C', 'hard'),
  ('C#', 'hard'),
  ('C++', 'hard'),
  ('PHP', 'hard'),
  ('HTML', 'hard'),
  ('CSS', 'hard'),
  ('React', 'hard'),
  ('React Native', 'hard'),
  ('Node.js', 'hard'),
  ('Next.js', 'hard'),
  ('Vue.js', 'hard'),
  ('Angular', 'hard'),
  ('Express.js', 'hard'),
  ('Spring Boot', 'hard'),
  ('Django', 'hard'),
  ('Flask', 'hard'),
  ('Laravel', 'hard'),
  ('Flutter', 'hard'),
  ('Bootstrap', 'hard'),
  ('Tailwind CSS', 'hard'),
  ('SQL', 'hard'),
  ('MySQL', 'hard'),
  ('PostgreSQL', 'hard'),
  ('MongoDB', 'hard'),
  ('Banco de dados', 'hard'),
  ('APIs REST', 'hard'),
  ('AWS', 'hard'),
  ('Azure', 'hard'),
  ('CI/CD', 'hard'),
  ('Lógica de programação', 'hard'),
  ('Programação orientada a objetos', 'hard'),
  ('Programação', 'hard'),
  ('Desenvolvimento web', 'hard'),
  ('Análise de dados', 'hard'),
  ('Machine Learning', 'hard'),
  ('Inteligência artificial', 'hard'),
  ('ETL', 'hard'),
  ('R', 'hard'),
  ('VBA', 'hard'),
  ('Selenium', 'hard'),
  ('Jest', 'hard'),
  ('Scrum', 'hard'),
  ('Kanban', 'hard'),
  ('Metodologias ágeis', 'hard'),
  ('Gestão de projetos', 'hard'),
  ('Segurança da informação', 'hard'),
  ('Redes de computadores', 'hard'),
  ('Manutenção de hardware', 'hard'),
  ('Suporte técnico', 'hard'),
  ('Edição de vídeo', 'hard'),
  ('Design', 'hard'),
  ('Marketing digital', 'hard'),
  ('Gestão de redes sociais', 'hard'),
  ('Criação de conteúdo', 'hard'),
  ('Storytelling', 'hard'),
  ('Modelagem financeira', 'hard'),
  ('Valuation', 'hard'),
  ('Matemática financeira', 'hard'),
  ('Contabilidade', 'hard'),
  ('Automação', 'hard'),
  ('Rotinas administrativas', 'hard'),
  ('Atendimento ao cliente', 'hard'),
  ('Controle de estoque', 'hard'),
  ('Operação de caixa', 'hard'),
  ('Contas a pagar', 'hard'),
  ('Controle financeiro', 'hard'),
  ('Departamento pessoal', 'hard'),
  ('Recrutamento e seleção', 'hard'),
  ('Gestão de pessoas', 'hard'),
  ('Recepção', 'hard'),
  ('Digitação', 'hard'),
  ('Vendas', 'hard'),
  ('Administração', 'hard'),
  ('Gestão documental', 'hard'),
  ('Inglês', 'language'),
  ('Trabalho em equipe', 'soft'),
  ('Comunicação', 'soft'),
  ('Oratória', 'soft'),
  ('Organização', 'soft'),
  ('Proatividade', 'soft'),
  ('Responsabilidade', 'soft'),
  ('Comprometimento', 'soft'),
  ('Pontualidade', 'soft'),
  ('Liderança', 'soft'),
  ('Criatividade', 'soft'),
  ('Empatia', 'soft'),
  ('Resiliência', 'soft'),
  ('Adaptabilidade', 'soft'),
  ('Aprendizado rápido', 'soft'),
  ('Resolução de problemas', 'soft'),
  ('Pensamento crítico', 'soft'),
  ('Raciocínio lógico', 'soft'),
  ('Atenção aos detalhes', 'soft'),
  ('Gestão de tempo', 'soft'),
  ('Relacionamento interpessoal', 'soft'),
  ('Escuta ativa', 'soft'),
  ('Inteligência emocional', 'soft'),
  ('Negociação', 'soft'),
  ('Foco em resultados', 'soft'),
  ('Dinamismo', 'soft'),
  ('Disciplina', 'soft'),
  ('Ética', 'soft'),
  ('Paciência', 'soft'),
  ('Dedicação', 'soft'),
  ('Tomada de decisão', 'soft'),
  ('Planejamento', 'soft')
on conflict (canonical_name) do nothing;

-- ── Seed: aliases (resolve canônica por nome) ─────────────────────────────────
insert into public.skill_aliases (alias_normalized, canonical_skill_id)
select v.alias, c.id
from (values
  ('excel', 'Excel'),
  ('microsoft excel', 'Excel'),
  ('ms excel', 'Excel'),
  ('exel', 'Excel'),
  ('excel avançado', 'Excel'),
  ('excel intermediário', 'Excel'),
  ('excel básico', 'Excel'),
  ('conhecimento básico em excel', 'Excel'),
  ('microsoft office (excel)', 'Excel'),
  ('pacote office (excel intermediário)', 'Excel'),
  ('word', 'Word'),
  ('microsoft word', 'Word'),
  ('word intermediário', 'Word'),
  ('powerpoint', 'PowerPoint'),
  ('power point', 'PowerPoint'),
  ('microsoft powerpoint', 'PowerPoint'),
  ('habilidade em powerpoint', 'PowerPoint'),
  ('outlook', 'Outlook'),
  ('microsoft outlook', 'Outlook'),
  ('pacote office', 'Pacote Office'),
  ('microsoft office', 'Pacote Office'),
  ('microsoft 365', 'Pacote Office'),
  ('pacote microsoft office', 'Pacote Office'),
  ('pacote office completo', 'Pacote Office'),
  ('pacote office intermediário', 'Pacote Office'),
  ('pacote office avançado', 'Pacote Office'),
  ('pacote office básico', 'Pacote Office'),
  ('domínio do pacote office', 'Pacote Office'),
  ('conhecimento do pacote office', 'Pacote Office'),
  ('conhecimento em pacote office', 'Pacote Office'),
  ('pacote office (word, excel, powerpoint)', 'Pacote Office'),
  ('pacote office (word, excel e powerpoint)', 'Pacote Office'),
  ('pacote office (excel, word e powerpoint)', 'Pacote Office'),
  ('pacote office (excel, word, powerpoint)', 'Pacote Office'),
  ('pacote office (word, excel e outlook)', 'Pacote Office'),
  ('pacote office (word, excel, powerpoint, outlook)', 'Pacote Office'),
  ('pacote office (excel e word)', 'Pacote Office'),
  ('microsoft office (word, excel e powerpoint)', 'Pacote Office'),
  ('google workspace', 'Google Workspace'),
  ('canva', 'Canva'),
  ('figma', 'Figma'),
  ('power bi', 'Power BI'),
  ('photoshop', 'Photoshop'),
  ('adobe photoshop', 'Photoshop'),
  ('illustrator', 'Illustrator'),
  ('adobe illustrator', 'Illustrator'),
  ('after effects', 'After Effects'),
  ('premiere', 'Premiere'),
  ('adobe premiere', 'Premiere'),
  ('pacote adobe', 'Pacote Adobe'),
  ('adobe creative cloud', 'Pacote Adobe'),
  ('capcut', 'CapCut'),
  ('git', 'Git'),
  ('github', 'Git'),
  ('git e github', 'Git'),
  ('git/github', 'Git'),
  ('versionamento de código', 'Git'),
  ('docker', 'Docker'),
  ('docker compose', 'Docker'),
  ('vs code', 'VS Code'),
  ('postman', 'Postman'),
  ('insomnia', 'Insomnia'),
  ('jira', 'Jira'),
  ('trello', 'Trello'),
  ('notion', 'Notion'),
  ('linux', 'Linux'),
  ('windows', 'Windows'),
  ('windows 10', 'Windows'),
  ('windows 11', 'Windows'),
  ('windows 10/11', 'Windows'),
  ('sistemas operacionais windows', 'Windows'),
  ('mac os', 'macOS'),
  ('autocad', 'AutoCAD'),
  ('revit', 'Revit'),
  ('sketchup', 'SketchUp'),
  ('solidworks', 'SolidWorks'),
  ('sap', 'SAP'),
  ('totvs', 'TOTVS'),
  ('salesforce', 'Salesforce'),
  ('servicenow', 'ServiceNow'),
  ('tableau', 'Tableau'),
  ('power automate', 'Power Automate'),
  ('power apps', 'Power Apps'),
  ('wordpress', 'WordPress'),
  ('vercel', 'Vercel'),
  ('vite', 'Vite'),
  ('maven', 'Maven'),
  ('intellij idea', 'IntelliJ IDEA'),
  ('microsoft teams', 'Microsoft Teams'),
  ('miro', 'Miro'),
  ('omie', 'Omie'),
  ('tasy', 'Tasy'),
  ('zabbix', 'Zabbix'),
  ('n8n', 'n8n'),
  ('obs studio', 'OBS Studio'),
  ('firebase', 'Firebase'),
  ('crm', 'CRM'),
  ('erp', 'ERP'),
  ('conhecimento intermediário em erp', 'ERP'),
  ('oracle', 'Oracle'),
  ('informática básica', 'Informática básica'),
  ('informática', 'Informática básica'),
  ('conhecimento básico em informática', 'Informática básica'),
  ('conhecimentos básicos em informática', 'Informática básica'),
  ('noções de informática', 'Informática básica'),
  ('informática avançada', 'Informática básica'),
  ('informática intermediária', 'Informática básica'),
  ('habilidades em informática', 'Informática básica'),
  ('conhecimento em informática', 'Informática básica'),
  ('conhecimentos em informática', 'Informática básica'),
  ('informática básica e avançada', 'Informática básica'),
  ('facilidade com tecnologia', 'Informática básica'),
  ('facilidade com sistemas e tecnologia', 'Informática básica'),
  ('facilidade com ferramentas digitais', 'Informática básica'),
  ('planilhas', 'Planilhas'),
  ('controle de planilhas', 'Planilhas'),
  ('python', 'Python'),
  ('programação em python', 'Python'),
  ('conhecimento em python', 'Python'),
  ('python (básico)', 'Python'),
  ('pandas', 'Python'),
  ('javascript', 'JavaScript'),
  ('java script', 'JavaScript'),
  ('js', 'JavaScript'),
  ('javascript (básico)', 'JavaScript'),
  ('typescript', 'TypeScript'),
  ('java', 'Java'),
  ('c', 'C'),
  ('c#', 'C#'),
  ('c++', 'C++'),
  ('php', 'PHP'),
  ('html', 'HTML'),
  ('html5', 'HTML'),
  ('html e css', 'HTML'),
  ('html & css', 'HTML'),
  ('html/css', 'HTML'),
  ('css', 'CSS'),
  ('css3', 'CSS'),
  ('react', 'React'),
  ('react.js', 'React'),
  ('react native', 'React Native'),
  ('node.js', 'Node.js'),
  ('nodejs', 'Node.js'),
  ('node js', 'Node.js'),
  ('next.js', 'Next.js'),
  ('vue.js', 'Vue.js'),
  ('angular', 'Angular'),
  ('express.js', 'Express.js'),
  ('spring boot', 'Spring Boot'),
  ('django', 'Django'),
  ('flask', 'Flask'),
  ('laravel', 'Laravel'),
  ('flutter', 'Flutter'),
  ('bootstrap', 'Bootstrap'),
  ('tailwind css', 'Tailwind CSS'),
  ('tailwindcss', 'Tailwind CSS'),
  ('sql', 'SQL'),
  ('sql server', 'SQL'),
  ('microsoft sql server', 'SQL'),
  ('pl/sql', 'SQL'),
  ('mysql', 'MySQL'),
  ('postgresql', 'PostgreSQL'),
  ('postgres', 'PostgreSQL'),
  ('mongodb', 'MongoDB'),
  ('banco de dados', 'Banco de dados'),
  ('modelagem de dados', 'Banco de dados'),
  ('modelagem de banco de dados', 'Banco de dados'),
  ('apis rest', 'APIs REST'),
  ('rest apis', 'APIs REST'),
  ('rest api', 'APIs REST'),
  ('aws', 'AWS'),
  ('azure', 'Azure'),
  ('ci/cd', 'CI/CD'),
  ('lógica de programação', 'Lógica de programação'),
  ('noções de lógica de programação', 'Lógica de programação'),
  ('programação orientada a objetos (poo)', 'Programação orientada a objetos'),
  ('solid', 'Programação orientada a objetos'),
  ('programação', 'Programação'),
  ('desenvolvimento web', 'Desenvolvimento web'),
  ('web design', 'Desenvolvimento web'),
  ('web designer', 'Desenvolvimento web'),
  ('análise de dados', 'Análise de dados'),
  ('machine learning', 'Machine Learning'),
  ('inteligência artificial', 'Inteligência artificial'),
  ('experiência com chatgpt', 'Inteligência artificial'),
  ('etl', 'ETL'),
  ('r', 'R'),
  ('vba', 'VBA'),
  ('selenium', 'Selenium'),
  ('jest', 'Jest'),
  ('scrum', 'Scrum'),
  ('kanban', 'Kanban'),
  ('metodologias ágeis', 'Metodologias ágeis'),
  ('gestão de projetos', 'Gestão de projetos'),
  ('segurança da informação', 'Segurança da informação'),
  ('noções de segurança da informação', 'Segurança da informação'),
  ('redes', 'Redes de computadores'),
  ('redes de computadores', 'Redes de computadores'),
  ('noções de redes', 'Redes de computadores'),
  ('manutenção de hardware', 'Manutenção de hardware'),
  ('montagem e manutenção de computadores', 'Manutenção de hardware'),
  ('suporte técnico', 'Suporte técnico'),
  ('suporte tecnico', 'Suporte técnico'),
  ('suporte técnico presencial e remoto', 'Suporte técnico'),
  ('edição de vídeo', 'Edição de vídeo'),
  ('videomaker', 'Edição de vídeo'),
  ('design', 'Design'),
  ('identidade visual', 'Design'),
  ('marketing digital', 'Marketing digital'),
  ('noções de marketing digital', 'Marketing digital'),
  ('marketing', 'Marketing digital'),
  ('gestão de redes sociais', 'Gestão de redes sociais'),
  ('social media', 'Gestão de redes sociais'),
  ('redes sociais', 'Gestão de redes sociais'),
  ('criação de conteúdo', 'Criação de conteúdo'),
  ('produção de conteúdo', 'Criação de conteúdo'),
  ('storytelling', 'Storytelling'),
  ('modelagem financeira', 'Modelagem financeira'),
  ('valuation', 'Valuation'),
  ('matemática financeira', 'Matemática financeira'),
  ('contabilidade', 'Contabilidade'),
  ('automação', 'Automação'),
  ('rotinas administrativas', 'Rotinas administrativas'),
  ('organização administrativa', 'Rotinas administrativas'),
  ('suporte administrativo', 'Rotinas administrativas'),
  ('gestão administrativa', 'Rotinas administrativas'),
  ('assistente administrativo', 'Rotinas administrativas'),
  ('organização e controle de processos', 'Rotinas administrativas'),
  ('organização e controle de informações', 'Rotinas administrativas'),
  ('controle de processos', 'Rotinas administrativas'),
  ('atendimento ao cliente', 'Atendimento ao cliente'),
  ('atendimento ao público', 'Atendimento ao cliente'),
  ('relacionamento com clientes', 'Atendimento ao cliente'),
  ('foco no cliente', 'Atendimento ao cliente'),
  ('facilidade com atendimento ao público', 'Atendimento ao cliente'),
  ('controle de estoque', 'Controle de estoque'),
  ('gestão de estoque', 'Controle de estoque'),
  ('organização e controle de estoque', 'Controle de estoque'),
  ('inventário', 'Controle de estoque'),
  ('operação de caixa', 'Operação de caixa'),
  ('conhecimento prático em operação de caixa', 'Operação de caixa'),
  ('contas a pagar', 'Contas a pagar'),
  ('controle financeiro', 'Controle financeiro'),
  ('faturamento', 'Controle financeiro'),
  ('emissão de notas fiscais', 'Controle financeiro'),
  ('departamento pessoal', 'Departamento pessoal'),
  ('recrutamento e seleção', 'Recrutamento e seleção'),
  ('gestão de pessoas', 'Gestão de pessoas'),
  ('recepção', 'Recepção'),
  ('digitação', 'Digitação'),
  ('digitação rápida', 'Digitação'),
  ('vendas', 'Vendas'),
  ('administração', 'Administração'),
  ('gestão documental', 'Gestão documental'),
  ('controle documental', 'Gestão documental'),
  ('organização de documentos', 'Gestão documental'),
  ('inglês', 'Inglês'),
  ('inglês avançado', 'Inglês'),
  ('inglês básico', 'Inglês'),
  ('inglês intermediário', 'Inglês'),
  ('trabalho em equipe', 'Trabalho em equipe'),
  ('atividades em grupo', 'Trabalho em equipe'),
  ('trabalho bem em equipe', 'Trabalho em equipe'),
  ('capacidade de trabalhar em equipe', 'Trabalho em equipe'),
  ('capacidade de trabalho em equipe', 'Trabalho em equipe'),
  ('facilidade para trabalhar em equipe', 'Trabalho em equipe'),
  ('facilidade em trabalhar em equipe', 'Trabalho em equipe'),
  ('facilidade para trabalho em equipe', 'Trabalho em equipe'),
  ('trabalho em equipe e colaboração', 'Trabalho em equipe'),
  ('comunicação e trabalho em equipe', 'Trabalho em equipe'),
  ('boa comunicação e trabalho em equipe', 'Trabalho em equipe'),
  ('comunicação eficaz e trabalho em equipe', 'Trabalho em equipe'),
  ('comunicação', 'Comunicação'),
  ('boa comunicação', 'Comunicação'),
  ('comunicação eficaz', 'Comunicação'),
  ('comunicação interpessoal', 'Comunicação'),
  ('comunicativa', 'Comunicação'),
  ('comunicativo', 'Comunicação'),
  ('comunicação clara', 'Comunicação'),
  ('comunicação assertiva', 'Comunicação'),
  ('comunicação eficiente', 'Comunicação'),
  ('comunicação oral e escrita', 'Comunicação'),
  ('comunicação verbal e escrita', 'Comunicação'),
  ('boa comunicação interpessoal', 'Comunicação'),
  ('boa comunicação verbal', 'Comunicação'),
  ('comunicação clara e objetiva', 'Comunicação'),
  ('comunicação eficaz escrita e verbal', 'Comunicação'),
  ('comunicação clara e cordial', 'Comunicação'),
  ('comunicação clara e empática', 'Comunicação'),
  ('comunicação clara e profissional', 'Comunicação'),
  ('comunicação institucional', 'Comunicação'),
  ('boa comunicação verbal e escrita', 'Comunicação'),
  ('excelente comunicação oral e escrita', 'Comunicação'),
  ('habilidade de comunicação', 'Comunicação'),
  ('competências de comunicação', 'Comunicação'),
  ('boa comunicação e relacionamento interpessoal', 'Comunicação'),
  ('boa comunicação e atendimento ao cliente', 'Comunicação'),
  ('boa comunicação e atendimento ao público', 'Comunicação'),
  ('boa comunicação com a equipe', 'Comunicação'),
  ('oratória', 'Oratória'),
  ('comunicação e oratória', 'Oratória'),
  ('organização', 'Organização'),
  ('organizado', 'Organização'),
  ('organizada', 'Organização'),
  ('organização e responsabilidade', 'Organização'),
  ('organização e atenção aos detalhes', 'Organização'),
  ('organização e atenção a detalhes', 'Organização'),
  ('organização e planejamento', 'Organização'),
  ('organização de processos', 'Organização'),
  ('organização e proatividade', 'Organização'),
  ('organização exemplar', 'Organização'),
  ('organização e gestão de tarefas', 'Organização'),
  ('organização e gestão de informações', 'Organização'),
  ('organização e disciplina', 'Organização'),
  ('organização e comprometimento', 'Organização'),
  ('organização e pontualidade', 'Organização'),
  ('competências organizacionais', 'Organização'),
  ('organização e cumprimento de prazos', 'Organização'),
  ('proatividade', 'Proatividade'),
  ('proativo', 'Proatividade'),
  ('proativa', 'Proatividade'),
  ('proatividade e responsabilidade', 'Proatividade'),
  ('proatividade e iniciativa', 'Proatividade'),
  ('proatividade e aprendizado rápido', 'Proatividade'),
  ('proatividade e disposição para aprender', 'Proatividade'),
  ('proatividade e facilidade de aprendizado', 'Proatividade'),
  ('responsabilidade', 'Responsabilidade'),
  ('responsável', 'Responsabilidade'),
  ('responsabilidade e comprometimento', 'Responsabilidade'),
  ('responsabilidade e pontualidade', 'Responsabilidade'),
  ('disciplina e responsabilidade', 'Responsabilidade'),
  ('comprometimento', 'Comprometimento'),
  ('comprometido', 'Comprometimento'),
  ('comprometimento e responsabilidade', 'Comprometimento'),
  ('comprometimento com resultados', 'Comprometimento'),
  ('comprometimento com metas e resultados', 'Comprometimento'),
  ('pontualidade', 'Pontualidade'),
  ('pontual', 'Pontualidade'),
  ('pontualidade e responsabilidade', 'Pontualidade'),
  ('liderança', 'Liderança'),
  ('criatividade', 'Criatividade'),
  ('criativo', 'Criatividade'),
  ('criativa', 'Criatividade'),
  ('pensamento criativo', 'Criatividade'),
  ('empatia', 'Empatia'),
  ('resiliência', 'Resiliência'),
  ('adaptabilidade', 'Adaptabilidade'),
  ('adaptação', 'Adaptabilidade'),
  ('fácil adaptação', 'Adaptabilidade'),
  ('facilidade de adaptação', 'Adaptabilidade'),
  ('flexibilidade', 'Adaptabilidade'),
  ('flexível', 'Adaptabilidade'),
  ('versatilidade', 'Adaptabilidade'),
  ('capacidade de adaptação', 'Adaptabilidade'),
  ('facilidade de aprendizado e adaptação', 'Adaptabilidade'),
  ('aprendizado rápido', 'Aprendizado rápido'),
  ('facilidade de aprendizado', 'Aprendizado rápido'),
  ('facilidade para aprender', 'Aprendizado rápido'),
  ('facilidade em aprender', 'Aprendizado rápido'),
  ('aprendizagem rápida', 'Aprendizado rápido'),
  ('rápido aprendizado', 'Aprendizado rápido'),
  ('fácil aprendizado', 'Aprendizado rápido'),
  ('vontade de aprender', 'Aprendizado rápido'),
  ('capacidade de aprendizado rápido', 'Aprendizado rápido'),
  ('capacidade de aprendizagem', 'Aprendizado rápido'),
  ('facilidade de aprendizagem', 'Aprendizado rápido'),
  ('aprendizado contínuo', 'Aprendizado rápido'),
  ('capacidade de aprender rapidamente', 'Aprendizado rápido'),
  ('capacidade de aprendizado contínuo', 'Aprendizado rápido'),
  ('facilidade de aprendizagem de novas funções', 'Aprendizado rápido'),
  ('resolução de problemas', 'Resolução de problemas'),
  ('solução de problemas', 'Resolução de problemas'),
  ('capacidade de resolver problemas', 'Resolução de problemas'),
  ('capacidade de investigação e resolução de problemas', 'Resolução de problemas'),
  ('pensamento crítico', 'Pensamento crítico'),
  ('raciocínio lógico', 'Raciocínio lógico'),
  ('atenção aos detalhes', 'Atenção aos detalhes'),
  ('gestão de tempo', 'Gestão de tempo'),
  ('gestão do tempo', 'Gestão de tempo'),
  ('gerenciamento de tempo', 'Gestão de tempo'),
  ('gestão de prazos', 'Gestão de tempo'),
  ('relacionamento interpessoal', 'Relacionamento interpessoal'),
  ('bom relacionamento interpessoal', 'Relacionamento interpessoal'),
  ('ótimo relacionamento interpessoal', 'Relacionamento interpessoal'),
  ('facilidade em lidar com pessoas', 'Relacionamento interpessoal'),
  ('escuta ativa', 'Escuta ativa'),
  ('inteligência emocional', 'Inteligência emocional'),
  ('negociação', 'Negociação'),
  ('persuasão', 'Negociação'),
  ('vendas e negociação', 'Negociação'),
  ('foco em resultados', 'Foco em resultados'),
  ('dinâmico', 'Dinamismo'),
  ('dinâmica', 'Dinamismo'),
  ('dinamismo', 'Dinamismo'),
  ('agilidade', 'Dinamismo'),
  ('disciplina', 'Disciplina'),
  ('ética', 'Ética'),
  ('paciência', 'Paciência'),
  ('dedicação', 'Dedicação'),
  ('tomada de decisões', 'Tomada de decisão'),
  ('planejamento', 'Planejamento')
) as v(alias, canon)
join public.skills_catalog c on c.canonical_name = v.canon
on conflict (alias_normalized) do nothing;

-- ── Trigger: normaliza canonical_skill_id em TODO write de name ───────────────
create or replace function public.set_canonical_skill_id() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  select a.canonical_skill_id into new.canonical_skill_id
  from public.skill_aliases a
  where a.alias_normalized = lower(btrim(new.name));
  return new;
end $$;

drop trigger if exists trg_profile_skills_canonical on public.profile_skills;
create trigger trg_profile_skills_canonical
  before insert or update of name on public.profile_skills
  for each row execute function public.set_canonical_skill_id();

-- ── Backfill das linhas existentes (não dispara o trigger: seta a coluna direto) ─
update public.profile_skills ps
set canonical_skill_id = a.canonical_skill_id
from public.skill_aliases a
where a.alias_normalized = lower(btrim(ps.name))
  and ps.canonical_skill_id is distinct from a.canonical_skill_id;
