-- ============================================
-- INCREMENTAL BULLET GENERATION - MIGRATION
-- ============================================
-- Run this in your Supabase SQL Editor
-- This adds the 3-layer data model for incremental CV generation:
--   Layer 1: user_experiences + experience_raw_responses (source of truth)
--   Layer 2: bullet_versions + approved_bullets (AI-generated, user-chosen)
--   Layer 3: section_versions (free-text sections like summary)
-- ============================================

-- ============================================
-- LAYER 1: EXPERIENCES & RAW RESPONSES
-- ============================================

-- User experiences (groups raw responses + bullets per experience)
CREATE TABLE IF NOT EXISTS user_experiences (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    experience_type TEXT NOT NULL, -- 'corporate', 'startup', 'freelance', 'social', 'academic', 'leadership', 'extracurricular'
    title TEXT, -- cargo or title
    organization TEXT, -- company, league, etc
    period TEXT,
    section TEXT NOT NULL DEFAULT 'experiencias', -- 'experiencias', 'projetos', 'formacao', 'lideranca'
    source_phase_id TEXT, -- phase that originated this (t3_p1, t2_p3, etc)
    source_question_id TEXT, -- specific question ID (M3_1_1_Q2_0, etc)
    display_order INT DEFAULT 0,
    is_included BOOLEAN DEFAULT true, -- user can exclude from CV without deleting
    raw_form_data JSONB, -- the full experienceForm JSON as submitted by user
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Raw responses (exact Q&A pairs for each experience — source of truth)
CREATE TABLE IF NOT EXISTS experience_raw_responses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    experience_id UUID NOT NULL REFERENCES user_experiences(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    question_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- LAYER 2: BULLET VERSIONS & APPROVED BULLETS
-- ============================================

-- All bullet versions generated by AI (keep ALL, not just chosen)
CREATE TABLE IF NOT EXISTS bullet_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    experience_id UUID NOT NULL REFERENCES user_experiences(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    angle TEXT NOT NULL CHECK (angle IN ('resultado', 'processo', 'habilidade')),
    version_number INT DEFAULT 1,
    model_used TEXT DEFAULT 'gpt-4o',
    prompt_version TEXT DEFAULT 'v1', -- track which prompt generated this
    tokens_used INT DEFAULT 0,
    confidence REAL DEFAULT 0.8, -- AI self-reported confidence (0.0 to 1.0)
    was_chosen BOOLEAN DEFAULT false,
    was_edited BOOLEAN DEFAULT false,
    edited_content TEXT, -- final content if user edited it
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Bullets approved by the user (what goes into the CV)
CREATE TABLE IF NOT EXISTS approved_bullets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    experience_id UUID NOT NULL REFERENCES user_experiences(id) ON DELETE CASCADE,
    bullet_version_id UUID REFERENCES bullet_versions(id), -- null if user wrote from scratch
    final_text TEXT NOT NULL,
    display_order INT DEFAULT 0,
    source TEXT NOT NULL DEFAULT 'ai_chosen' CHECK (source IN ('ai_chosen', 'ai_edited', 'user_written', 'ai_mixed')),
    approved_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- LAYER 3: FREE-TEXT SECTION VERSIONS
-- ============================================

-- Versions for free-text sections (resumo_profissional, habilidades, interesses)
CREATE TABLE IF NOT EXISTS section_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    section_type TEXT NOT NULL, -- 'resumo_profissional', 'habilidades', 'interesses'
    content TEXT NOT NULL,
    angle TEXT, -- nullable for sections without angle
    version_number INT DEFAULT 1,
    model_used TEXT DEFAULT 'gpt-4o',
    was_chosen BOOLEAN DEFAULT false,
    was_edited BOOLEAN DEFAULT false,
    edited_content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- AI GENERATION LOG (enhanced)
-- ============================================

-- Add bullet-specific generation tracking
-- (existing ai_generation_logs table is kept for backward compat)
CREATE TABLE IF NOT EXISTS bullet_generation_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    experience_id UUID NOT NULL REFERENCES user_experiences(id) ON DELETE CASCADE,
    generation_type TEXT NOT NULL DEFAULT 'bullets', -- 'bullets', 'deepening', 'regeneration'
    model_used TEXT DEFAULT 'gpt-4o',
    prompt_version TEXT DEFAULT 'v1',
    input_tokens INT DEFAULT 0,
    output_tokens INT DEFAULT 0,
    total_tokens INT DEFAULT 0,
    latency_ms INT, -- response time in milliseconds
    had_clarification BOOLEAN DEFAULT false, -- did the AI request needs_clarification?
    clarification_question TEXT, -- what it asked
    clarification_answered BOOLEAN DEFAULT false, -- did the user respond?
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX IF NOT EXISTS idx_experiences_user ON user_experiences(user_id);
CREATE INDEX IF NOT EXISTS idx_experiences_phase ON user_experiences(source_phase_id);
CREATE INDEX IF NOT EXISTS idx_raw_responses_exp ON experience_raw_responses(experience_id);
CREATE INDEX IF NOT EXISTS idx_bullet_versions_exp ON bullet_versions(experience_id);
CREATE INDEX IF NOT EXISTS idx_bullet_versions_chosen ON bullet_versions(experience_id) WHERE was_chosen = true;
CREATE INDEX IF NOT EXISTS idx_approved_user ON approved_bullets(user_id);
CREATE INDEX IF NOT EXISTS idx_approved_exp ON approved_bullets(experience_id);
CREATE INDEX IF NOT EXISTS idx_sections_user ON section_versions(user_id);
CREATE INDEX IF NOT EXISTS idx_bullet_logs_user ON bullet_generation_logs(user_id);

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

ALTER TABLE user_experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE experience_raw_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE bullet_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE approved_bullets ENABLE ROW LEVEL SECURITY;
ALTER TABLE section_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE bullet_generation_logs ENABLE ROW LEVEL SECURITY;

-- user_experiences: users manage their own
CREATE POLICY "Users manage own experiences" ON user_experiences
    FOR ALL USING (auth.uid() = user_id);

-- experience_raw_responses: access via experience ownership
CREATE POLICY "Users manage own raw responses" ON experience_raw_responses
    FOR ALL USING (
        experience_id IN (SELECT id FROM user_experiences WHERE user_id = auth.uid())
    );

-- bullet_versions: access via experience ownership
CREATE POLICY "Users manage own bullet versions" ON bullet_versions
    FOR ALL USING (
        experience_id IN (SELECT id FROM user_experiences WHERE user_id = auth.uid())
    );

-- approved_bullets: users manage their own
CREATE POLICY "Users manage own approved bullets" ON approved_bullets
    FOR ALL USING (auth.uid() = user_id);

-- section_versions: users manage their own
CREATE POLICY "Users manage own section versions" ON section_versions
    FOR ALL USING (auth.uid() = user_id);

-- bullet_generation_logs: users can view their own
CREATE POLICY "Users view own bullet logs" ON bullet_generation_logs
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- TRIGGER: auto-update updated_at on user_experiences
-- ============================================

CREATE TRIGGER update_user_experiences_updated_at
    BEFORE UPDATE ON user_experiences
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- DONE!
-- ============================================
